name: Build, lint and test
run-name: Build, lint and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Install modules
        run: yarn install
      - name: Create build
        run: yarn build
      - name: Lint
        run: yarn eslint
      - name: Run tests
        run: yarn test
