name: Publish
run-name: Publish package to NPM
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  USER_NAME: ${{ secrets.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ssh-key: "${SSH_KEY}"
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - name: Set user name and email
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_EMAIL}"
      - name: Checkout to main
        run: git checkout main
      - name: Set yarn config
        run: yarn config set version-git-message "[ci skip] %s"
      - name: Publish
        run: yarn ci:publish
      - name: Pull and rebase
        run: git pull --rebase
      - name: Push
        run: git push
