name: Publish package to GitHub Packages
run-name: Publish package to GitHub Packages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@crapstar"
      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
      - name: Publish
        run: 'git checkout main && yarn config set version-git-message "[ci skip] %s" && yarn ci:publish && git pull --rebase && git push'
